### ISSUE TITLE
`monit-docker` listed as zombie process

### ISSUE THREAD

**Issue by pat-s** [decryptus/monit-docker#2]
```
ps axo stat,ppid,pid,comm | grep -w defunct
Zs     14452   14895 monit-docker <defunct>
Zs     14452   14896 monit-docker <defunct>
```

After killing the parent process (14452 here), monit-docker starts up again and is again listed as a zombie process by the system.

Is there a way to prevent this? This started occuring a few days ago - before, everything was fine.

**Comment by decryptus** [comment]
Hi @pat-s 

Could you give me the python version and monit-docker version, plz?

**Comment by pat-s** [comment]
Should be the bundled python3 in the alpine image and the last monit version.

FWIW this also happens if monit-docker is installed on the host directly via pip and hence I think its unrelated to any of these versions.

**Comment by decryptus** [comment]
Ok, thx @pat-s I will try to reproduce the bug.
Could you tell me if there were any differences between the version with problem and the version without problem?
If so, could you give me the two versions of monit-docker?
Thank you

**Comment by pat-s** [comment]
> Could you tell me if there were any differences between the version with problem and the version without problem?

Ugh, I don't remember sorry - too long ago :)

But I am usually on the latest versions and doing automatic upgrades so I assume it was the latest version at this point in time (Jan 27th).

I am not sure if this is really a problem as I did not experience practical problems but I am also not experienced with the impact of zombie processes.
