### ISSUE TITLE
Generate pidfile for a running container

### ISSUE THREAD

**Issue by kfeina** [decryptus/monit-docker#3]
Hello, this is a new feature request I think it can be very useful. 
Basicallly the idea is to know when a container is restarted. 

The main idea  is to generate a pid file for a running container, so we can really monitor it with monit/mmonit. 

The followin command returns the real pid of a running container: 
docker inspect -f '{{.State.Pid}}' container_name 

I would like an option like  --piidfile in your monit-docker program. That way, to get an alert would be very easy: 

check process my_pid_container with pidfile /var/run/my_pid_container.pid
   if changed pid then alert

Do you think that is possible to make this feature ? 
Thaks a lot for your time.

**Comment by decryptus** [comment]
Hi @kfeina 

Yes, it's a good idea, I will do it.

**Comment by kfeina** [comment]
Hello, 

Let me know when it is done. I will test it. 

Thank you.

**Comment by decryptus** [comment]
Hi, @kfeina,

You will able to check pidfile with the version 0.0.41.
